### ISSUE TITLE
.json decode error

### ISSUE THREAD

**Issue by jfparisi** [pabloprf/MITIM-fusion#6]
Format of config_user.json file has issues on PPPL's spark cluster. Using the suggested template (just for .json format testing) @(https://mitim-fusion.readthedocs.io/en/latest/installation.html#instructions)
```
"preferences": {
   "tglf":             "engaging",
   "verbose_level":    "5",
   "dpi_notebook":     "80"
},
"engaging": {
   "machine":          "eofe7.mit.edu",
   "username":         "pablorf",
   "partition":        "sched_mit_psfc",
   "identity":         "~/.ssh/id_rsa",
   "scratch":          "/nobackup1/pablorf/scratch/"
   }
```
and running
```
python3 $MITIM_PATH/tests/TGLF_workflow.py
```
gives error
```
(mitim-env) [jparisi@spark-login2 MITIM-fusion-spark]$ python3 $MITIM_PATH/tests/TGLF_workflow.py
Traceback (most recent call last):
  File "/p/gyro/jparisi/MITIM-fusion-spark/tests/TGLF_workflow.py", line 2, in <module>
    from mitim_tools.misc_tools import IOtools
  File "/p/gyro/jparisi/MITIM-fusion-spark/src/mitim_tools/misc_tools/IOtools.py", line 19, in <module>
    verbose_level = read_verbose_level()
  File "/p/gyro/jparisi/MITIM-fusion-spark/src/mitim_tools/misc_tools/CONFIGread.py", line 21, in read_verbose_level
    s = load_settings()
  File "/p/gyro/jparisi/MITIM-fusion-spark/src/mitim_tools/misc_tools/CONFIGread.py", line 15, in load_settings
    settings = json.load(f)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 14 (char 13)
```

**Comment by jfparisi** [comment]
This seems to be fixed by small change to formatting:
```
{
  "preferences": {
    "tglf": "engaging",
    "verbose_level": "5",
    "dpi_notebook": "80"
  },
  "engaging": {
    "machine": "eofe7.mit.edu",
    "username": "pablorf",
    "partition": "sched_mit_psfc",
    "identity": "~/.ssh/id_rsa",
    "scratch": "/nobackup1/pablorf/scratch/"
  }
}
```

**Comment by jfparisi** [comment]
Closing issue.

**Comment by pabloprf** [comment]
Interesting... was it the spaces vs tabs?

**Comment by jfparisi** [comment]
It was the extra set of parentheses. In config_user_example.json, you had it right; it was just the .json example on https://mitim-fusion.readthedocs.io/en/latest/installation.html#instructions that needed an extra set of {}.
